name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Test with LocalStack
      run: |
        docker-compose -f docker-compose.yml up -d
        sleep 30
        python setup_localstack.py
        mvn test
        docker-compose -f docker-compose.yml down

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: order-service
        path: target/order-service-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: order-service

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.EC2_INSTANCE_IP }}
        username: ${{ secrets.EC2_INSTANCE_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          pkill -f 'java -jar' || true
          nohup java -jar order-service-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
