name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Test with LocalStack
      run: |
        docker-compose -f docker-compose.yml up -d
        sleep 30
        python setup_localstack.py
        mvn test
        docker-compose -f docker-compose.yml down

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: order-service
        path: target/order-service-0.0.1-SNAPSHOT.jar
