version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - mynetwork

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,dynamodb,s3,iam
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - mynetwork

  order-service:
    build:
      context: order-service/
      dockerfile: Dockerfile
    image: felipedev21/spring-ops-order-service:latest
    container_name: order-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - AWS_DYNAMODB_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
      - localstack
      - api-gateway
      - service-discovery
    networks:
      - mynetwork

  api-gateway:
    build:
      context: api-gateway/
      dockerfile: Dockerfile
    image: felipedev21/spring-ops-api-gateway:latest
    container_name: api-gateway
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery
    networks:
      - mynetwork

  service-discovery:
    build:
      context: service-discovery/
      dockerfile: Dockerfile
    image: felipedev21/spring-ops-service-discovery:latest
    container_name: service-discovery
    environment:
      - SPRING_APPLICATION_NAME=service-discovery
    ports:
      - "8761:8761"
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Defina a senha de administrador
    ports:
      - "3000:3000"
    volumes:
      - ./datasource.yml:/etc/grafana/datasource.yml
    depends_on: 
      - order-service
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

volumes:
  postgres_data:
  rabbitmq_data:
  localstack_data:

networks:
  mynetwork:
