services:
  # 1. CAMADA DE INFRAESTRUTURA
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orderdb"]
      interval: 10s
      timeout: 5s
      retries: 5

# ADICIONE ESTES SERVIÇOS E REMOVA O RABBITMQ
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Configuração para o modo KRaft (sem Zookeeper)
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER # <-- A LINHA QUE FALTAVA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Configuração do Broker
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - mynetwork

  # Ferramenta de UI para visualizar os tópicos e mensagens do Kafka (muito útil!)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8989:8080" # Acesse em http://localhost:8989
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - mynetwork

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,dynamodb,s3,iam
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - mynetwork
    # Healthcheck para LocalStack é mais complexo, mas para desenvolvimento
    # a inicialização dele costuma ser rápida.

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. CAMADA DE PLATAFORMA / ORQUESTRAÇÃO
  service-discovery:
    build:
      context: service-discovery/
      dockerfile: Dockerfile
    container_name: service-discovery
    ports:
      - "8761:8761"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 5s
      retries: 10

  # 3. CAMADA DE APLICAÇÃO (MICROSSERVIÇOS)

  product-catalog-service:
    build:
      context: product-catalog-service/
      dockerfile: Dockerfile
    container_name: product-catalog-service
    ports:
      - "8083:8083" # Expondo a nova porta
    networks:
      - mynetwork
    depends_on:
      postgres:
        condition: service_healthy
      service-discovery:
        condition: service_healthy

  inventory-service:
    build:
      context: inventory-service/
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "8084:8084" # Expondo a nova porta
    networks:
      - mynetwork
    depends_on:
      redis:
        condition: service_healthy
      service-discovery:
        condition: service_healthy


  # 4. CAMADA DE BORDA E MONITORAMENTO
  api-gateway:
    build:
      context: api-gateway/
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      service-discovery:
        condition: service_healthy
      inventory-service:
        condition: service_started # Depende do serviço estar iniciado, não necessariamente healthy
      product-catalog-service:
        condition: service_started
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus
    container_name: prometheus-spring
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana
    container_name: grafana-spring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      # Aponte para o arquivo de configuração do datasource. Verifique se o nome do arquivo está correto.
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prometheus
    networks:
      - mynetwork

volumes:
  postgres_data:
  localstack_data:
  grafana_data:

networks:
  mynetwork: