server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v1/orders/**


eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/


 