server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: order-service
        uri: lb://order-service # "lb" significa load-balanced, o Gateway usará o Eureka para encontrar o serviço
        predicates:
          - Path=/v1/orders/**
      
      - id: product-catalog-service
        uri: lb://product-catalog-service
        predicates:
          - Path=/v1/api/products/**
      
      - id: inventory-service
        uri: lb://inventory-service
        predicates:
          - Path=/v1/api/inventory/**
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

# Expor todos os endpoints do Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
# Habilitar endpoint Prometheus
  endpoint:
    prometheus:
      enabled: true