pipeline{
    agent any

    stages {
        stage('Build'){
            steps{
                sh 'mvn clean package'
            }
        }
        stage('Test'){
            steps{
                sh 'mvn test'
            }
        }
        stage('Build Docker Image'){
            steps{
                sh 'docker build -t felipedev21/order-service:latest .'
            }
        }
        stage('Deploy to Docker'){
            steps{
                sh 'docker-compose up -d'
            }
        }
            
    }
}