global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'  # Caminho correto das métricas para Spring Boot com Actuator e Prometheus
    static_configs:
      - targets: ['order-service:8081', 'api-gateway:8080']
